services:
    - type: web
      name: resume-scorer-api
      env: python
      buildCommand: bash render-build.sh
      startCommand: python run_api.py --port=$PORT --host=0.0.0.0
      envVars:
          - key: PYTHON_VERSION
            value: 3.10.0
          - key: PORT
            value: 8000
      plan: free
      disk:
          name: resume-scorer-data
          mountPath: /data
          sizeGB: 2
