services:
    # A web service to run the resume analyzer app
    - type: web
      name: resume-scorer-api
      env: python
      region: singapore
      plan: free
      buildCommand: "./render-build.sh"
      startCommand: "./startup.sh"
      envVars:
          - key: PYTHON_VERSION
            value: 3.10.8
          - key: PORT
            value: 8080
          - key: ENVIRONMENT
            value: production
          - key: RENDER
            value: true
          - key: PYTHONUNBUFFERED
            value: true
          # Disable CUDA completely
          - key: CUDA_VISIBLE_DEVICES
            value: ""
          - key: FORCE_CPU
            value: 1
          - key: NO_CUDA
            value: 1
          # Optimize memory usage
          - key: PYTHONMALLOC
            value: malloc
          - key: MALLOC_TRIM_THRESHOLD_
            value: 65536
          - key: PYTORCH_JIT
            value: 0
          # Workers and threads
          - key: OMP_NUM_THREADS
            value: 1
          - key: MKL_NUM_THREADS
            value: 1
          # Skip problematic dependencies
          - key: SKIP_ONNX
            value: 1
      healthCheckPath: /health

# A Redis instance for job queuing (optional, use if you need background processing)
databases:
    - name: resume-queue
      plan: free
