services:
    # A web service to run the resume analyzer app
    - type: web
      name: resume-scorer-api
      env: python
      region: singapore
      plan: free
      buildCommand: "./render-build.sh"
      startCommand: "python run_api.py --port=$PORT --host=0.0.0.0 --workers=1 --use-render --preload-models --use-quantization --task-specific-models --optimize-memory --fallback-to-cpu --skip-onnx"
      envVars:
          - key: PYTHON_VERSION
            value: 3.10.8
          - key: PORT
            value: 8080
          - key: ENVIRONMENT
            value: production
          - key: RENDER
            value: true
          - key: TRANSFORMERS_OFFLINE
            value: 1
          - key: HF_DATASETS_OFFLINE
            value: 1
          - key: PYTHONUNBUFFERED
            value: true
          # Optimize Python memory usage
          - key: PYTHONMALLOC
            value: malloc
          - key: MALLOC_TRIM_THRESHOLD_
            value: 65536
          # Disable JIT compilation to save memory
          - key: PYTORCH_JIT
            value: 0
          # Keep memory footprint small
          - key: OMP_NUM_THREADS
            value: 1
          - key: MKL_NUM_THREADS
            value: 1
          # Optimize garbage collection
          - key: PYTHONGC
            value: threshold-aggressive
          # Increase memory reclamation
          - key: TORCH_EXTENSIONS_CACHE
            value: /tmp/torch_extensions
          # Enable model optimizations
          - key: USE_QUANTIZED_MODEL
            value: 1
          - key: USE_TASK_SPECIFIC_MODELS
            value: 1
          - key: OPTIMIZE_MEMORY
            value: 1
          - key: MEMORY_CONSTRAINED
            value: 1
          - key: CUDA_VISIBLE_DEVICES
            value: ""
          - key: MODEL_WARMUP_ON_START
            value: true
          - key: ENABLE_DYNAMIC_RESOURCE_MANAGEMENT
            value: true
          # Skip problematic dependencies
          - key: SKIP_ONNX
            value: 1
          # Retry settings for model loading
          - key: MODEL_LOAD_RETRIES
            value: 3
          # Tokenizer settings to reduce memory usage
          - key: TOKENIZERS_PARALLELISM
            value: false
      healthCheckPath: /health

# A Redis instance for job queuing (optional, use if you need background processing)
databases:
    - name: resume-queue
      plan: free
